# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [5]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [10]:
# your code here
print(np.version)

<module 'numpy.version' from '/Users/zenayela.soares/opt/anaconda3/lib/python3.8/site-packages/numpy/version.py'>


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [22]:
# Method 1 
a = np.random.random([2,3,5])
print(a)

[[[0.7662386  0.10288883 0.69492425 0.18552894 0.79600245]
  [0.96200611 0.68601112 0.19580688 0.12738344 0.20729727]
  [0.44004114 0.71377507 0.90729803 0.32396534 0.31710667]]

 [[0.1228586  0.35788895 0.12554172 0.69966149 0.00774494]
  [0.55623637 0.81617047 0.33276541 0.38830058 0.29759476]
  [0.52779645 0.52865891 0.90257817 0.01657726 0.05090027]]]


In [ ]:
# Method 2



In [ ]:
# Method 3

#### 4. Print *a*.


In [23]:
# your code here
a

array([[[0.7662386 , 0.10288883, 0.69492425, 0.18552894, 0.79600245],
        [0.96200611, 0.68601112, 0.19580688, 0.12738344, 0.20729727],
        [0.44004114, 0.71377507, 0.90729803, 0.32396534, 0.31710667]],

       [[0.1228586 , 0.35788895, 0.12554172, 0.69966149, 0.00774494],
        [0.55623637, 0.81617047, 0.33276541, 0.38830058, 0.29759476],
        [0.52779645, 0.52865891, 0.90257817, 0.01657726, 0.05090027]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [25]:
# your code here

b = np.ones((5,2,3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 6. Print *b*.


In [26]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [27]:
# your code here

a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [29]:
# your answer here

a.shape

(2, 3, 5)

In [30]:
b.shape

(5, 2, 3)

In [31]:
# We are not able to add a and b because their shape are different

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [37]:
# your code here

a.shape

(2, 3, 5)

In [43]:
a+b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [38]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [42]:
c = b.transpose(1,2,0)
c

# Etant donné que c'est une transposition, on doit changer la place des axex pour qu'elles correspondent. 

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [45]:
# your code/answer here

d = a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [47]:
# your code/answer here
a

array([[[0.7662386 , 0.10288883, 0.69492425, 0.18552894, 0.79600245],
        [0.96200611, 0.68601112, 0.19580688, 0.12738344, 0.20729727],
        [0.44004114, 0.71377507, 0.90729803, 0.32396534, 0.31710667]],

       [[0.1228586 , 0.35788895, 0.12554172, 0.69966149, 0.00774494],
        [0.55623637, 0.81617047, 0.33276541, 0.38830058, 0.29759476],
        [0.52779645, 0.52865891, 0.90257817, 0.01657726, 0.05090027]]])

In [48]:
d

array([[[1.7662386 , 1.10288883, 1.69492425, 1.18552894, 1.79600245],
        [1.96200611, 1.68601112, 1.19580688, 1.12738344, 1.20729727],
        [1.44004114, 1.71377507, 1.90729803, 1.32396534, 1.31710667]],

       [[1.1228586 , 1.35788895, 1.12554172, 1.69966149, 1.00774494],
        [1.55623637, 1.81617047, 1.33276541, 1.38830058, 1.29759476],
        [1.52779645, 1.52865891, 1.90257817, 1.01657726, 1.05090027]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [49]:
# your code here

e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [50]:
# your code/answer here
e

array([[[0.7662386 , 0.10288883, 0.69492425, 0.18552894, 0.79600245],
        [0.96200611, 0.68601112, 0.19580688, 0.12738344, 0.20729727],
        [0.44004114, 0.71377507, 0.90729803, 0.32396534, 0.31710667]],

       [[0.1228586 , 0.35788895, 0.12554172, 0.69966149, 0.00774494],
        [0.55623637, 0.81617047, 0.33276541, 0.38830058, 0.29759476],
        [0.52779645, 0.52865891, 0.90257817, 0.01657726, 0.05090027]]])

In [51]:
a

array([[[0.7662386 , 0.10288883, 0.69492425, 0.18552894, 0.79600245],
        [0.96200611, 0.68601112, 0.19580688, 0.12738344, 0.20729727],
        [0.44004114, 0.71377507, 0.90729803, 0.32396534, 0.31710667]],

       [[0.1228586 , 0.35788895, 0.12554172, 0.69966149, 0.00774494],
        [0.55623637, 0.81617047, 0.33276541, 0.38830058, 0.29759476],
        [0.52779645, 0.52865891, 0.90257817, 0.01657726, 0.05090027]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [56]:
# your code here

np.min(d)

1.0077449370862421

In [57]:
np.max(d)

1.9620061100270885

In [58]:
np.mean(d)

1.4385849500995278

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here